[project]
name = "ricoh-theta-mjpeg-opencv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.24.3",
    "opencv-python==4.7.0.72",
    "requests-auth==7.0.0",
    "requests==2.30.0",
]
